# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('unexcused', 'Unexcused'), ('excused', 'Excused'), ('late', 'Late')], max_length=10, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, choices=[('c', 'CITE '), ('a', 'CBA '), ('b', 'ASCEND ')], default='c', help_text='Book availability', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(help_text='Enter your Last_name ', max_length=100)),
                ('First_name', models.CharField(help_text='Enter your First name ', max_length=200)),
                ('MI', models.CharField(help_text='Enter your Middle Name', max_length=200)),
                ('Sex', models.CharField(blank=True, choices=[('m', 'Male'), ('F', 'Female')], default='m', max_length=1)),
            ],
        ),
    ]
