# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Department',
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('CITE', 'CITE'), ('CBA', 'CBA'), ('ASCEND', 'ASCEND')], default=1, max_length=10, verbose_name=''),
            preserve_default=False,
        ),
    ]
