# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendace', '0002_auto_20171120_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
